name: Proxy Scraper
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Scraper
      run: python scraper.py
